name: stream_analytics_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - numpy=1.24.4
  - notebook=7.0.6
  - jupyterlab=4.0.9
  - jupyter_core=5.5.0
  - pandas=2.0.3
  - pip=23.2.1
  - scikit-learn=1.3.2
  - pip:
      - fastavro==1.9.3
      - faker==22.7.0
